### ISSUE TITLE
Показывать больше информации об ошибке загрузки файла

### ISSUE THREAD

**Issue by miroque** [ioplker/plantuml-highlight#12]
### Что происходит
Когда загружается файл, и программа не может его открыть она сигнализирует надписью "ошибка"

из нее ни чего не понять, почему так? так как файл svg открывается в других программах

### Что хочется
Чтоб ошибка информировала больше. И можно было или руками поправить или еще что-то предпринять.

**Comment by ioplker** [comment]
Поправил, в планах показывать дамп основных объектов, но пока отображается только текст ошибки )
